services:

  db:
    image: postgres
    container_name: db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: wadmin
      POSTGRES_PASSWORD: PosTR45#^DBphIII*
      POSTGRES_DB: Databases-Project
    volumes:
      - ./DB:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build: .
    container_name: flask
    restart: always
    environment:
      DATABASE_URL: postgresql://wadmin:PosTR45#^DBphIII*@db:5432/Databases-Project
    volumes:
      - ./app:/app # Mount Python workspace
    depends_on:
      - db
    ports:
      - 80:5000